### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos_qc#103]
It would be beneficial if there was guidance for how folks can contribute to this repository. 

See https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

I am willing to take a stab at it so it's not starting from a blank slate.

**Comment by ocefpaf** [comment]
@MathewBiddle not sure if you already have something in mind but here are my two cents:

1. The metpy contributing docs are great and we could steal some of their text;
2. Maybe we could create something that applies to all IOOS projects.

**Comment by MathewBiddle** [comment]
I like the idea of 2, but I wonder about the feasibility. If you don't mind drafting some content, I can take a look. 

Initially I was going to copy https://github.com/ioos/bio_mobilization_workshop/blob/main/CONTRIBUTING.md and update the **Where to contribute** section.

**Comment by ocefpaf** [comment]
> Initially I was going to copy https://github.com/ioos/bio_mobilization_workshop/blob/main/CONTRIBUTING.md and update the **Where to contribute** section.

That is kind of aimed at documentation text. The one I mentioned has a bit more on how to clone, run tests, report bugs, etc. See https://github.com/Unidata/MetPy/blob/main/CONTRIBUTING.md

> I'm interested in this for the glider-dac repo.

I can send a PR with a modified version to https://github.com/ioos/.github and we can add links to it from the various IOOS repo. (I'm not sure if that propagates like the issue/PR template.)

**Comment by MathewBiddle** [comment]
> I can send a PR with a modified version to https://github.com/ioos/.github and we can add links to it from the various IOOS repo. (I'm not sure if that propagates like the issue/PR template.)

sounds good to me. At least it will provide a place to copy from at a minimum.

**Comment by MathewBiddle** [comment]
@ocefpaf that contributing guide doesn't appear in this repository. Should we just copy it from https://github.com/ioos/.github/blob/main/CONTRIBUTING.md ? Or is there a way to point to our org contributing guide?

**Comment by ocefpaf** [comment]
> @ocefpaf that contributing guide doesn't appear in this repository. Should we just copy it from https://github.com/ioos/.github/blob/main/CONTRIBUTING.md ? Or is there a way to point to our org contributing guide?

I guess we have to link it in the README or copy it over. I could not find any special treatment on GH's part for this but I recall there are open issues to requesting it.

**Comment by Sakshamgupta90** [comment]
> I guess we have to link it in the README or copy it over. I could not find any special treatment on GH's part for this but I recall there are open issues to requesting it.

Hi @ocefpaf 
Is it fine if I refer to https://github.com/ioos/.github/blob/main/CONTRIBUTING.md and https://github.com/Unidata/MetPy/blob/main/CONTRIBUTING.md, and copy the relevant information?

**Comment by ocefpaf** [comment]
You can start by copying https://github.com/ioos/.github/blob/main/CONTRIBUTING.md and modify it to be more "ioos_qc" specific.

**Comment by ocefpaf** [comment]
Done in #120.
