### ISSUE TITLE
Incorrect command in documentation

### ISSUE THREAD

**Issue by Sakshamgupta90** [ioos/ioos_qc#109]
The docs/source/development.rst file currently instructs users to install dependencies using the following commands:

``` conda install --file requirements.txt --file tests/requirements.txt``` and 
```conda install -y --file requirements.txt \  --file tests/requirements.txt \ --file docs/requirements.txt ```
        
However, these commands are incorrect. It should be:

```conda install --file requirements.txt --file requirements-dev.txt``` and 
```conda install -y --file requirements.txt \ --file requirements-dev.txt \ --file docs/requirements.txt```

I suggest updating the documentation to reflect the correct command for installing dependencies.

**Comment by srstsavage** [comment]
Thanks for reporting, would you like to submit a pull request with the correction?

**Comment by Sakshamgupta90** [comment]
Sure, will do that.

**Comment by srstsavage** [comment]
Fixed by #110. Thank you for your contribution!
