### ISSUE TITLE
QcConfig does not create an aggregate flag

### ISSUE THREAD

**Issue by cseaton** [ioos/ioos_qc#15]
If QcConfig ran qartod.qartod_compare to generate an aggregate flag for all of the tests run on a specific variable, and if NcQcConfig collected this as part of the run function and output it in the netcdf file in save_to_netcdf, then it would provide a standardized aggregate QC flag.

**Comment by jessicaaustin** [comment]
https://github.com/ioos/ioos_qc/pull/23 resolves this for `QcConfig`.

Still outstanding: add option to generate aggregate flag for `NcQcConfig`. That will be in a separate PR.
