### ISSUE TITLE
attenuated_signal_test flag logic for fail and suspect does not reflect manual

### ISSUE THREAD

**Issue by yosoyjay** [ioos/ioos_qc#17]
The `attenuated_signal_test` should test for values that fall below a larger suspect threshold and then a smaller fail threshold.

from `qartod.py`:
```
if check_val < threshold.maxv:
    flag_arr.fill(QartodFlags.FAIL)
elif check_val < threshold.minv:
    flag_arr.fill(QartodFlags.SUSPECT)
```

The thresholds should be swapped.

**Comment by kwilcox** [comment]
Fixed in https://github.com/ioos/ioos_qc/pull/12
