### ISSUE TITLE
Docs should use markdown instead of ReStructuredText

### ISSUE THREAD

**Issue by jessicaaustin** [ioos/ioos_qc#20]
https://www.sphinx-doc.org/en/master/usage/markdown.html

See instructions on how to build docs locally here: https://ioos.github.io/ioos_qc/installation.html#development-and-testing

PRs accepted!

**Comment by kwilcox** [comment]
Markdown is great for super simple formatting but anything a tad more complicated (tables, intra-linking, anchors, re-usable varaibles, etc.) isn't possible AFAIK.

Level 1 - Documentarist using Markdown
... a few hours...
Level 10 - Super Archivist using rST

It's worth every second.
