### ISSUE TITLE
Add Density Inversion Test

### ISSUE THREAD

**Issue by JessyBarrette** [ioos/ioos_qc#43]
The Hakai Institute is hoping to integrate the ioos_qc system into its workflow. 

One first application is to apply multiple QARTOD tests to our [Provisional CTD Profile Timeseries dataset](https://catalogue.hakai.org/erddap/tabledap/HakaiCTDProvisional.html) which is a ragged array representation of time series profiles that are submitted by field technicians and automatically processed by our internal system. We hope to automatically QAQC each profile by using a series of QARTOD tests for each variable. We are currently aiming are running the tests by loading the data from our database to a pandas Dataframe which would be used to apply the diverse tests and then submitting an aggregated QARTOD flag value for each variable back to our database. Which is then served to users with the previously shown ERDDAP dataset.

One very important test regarding CTD profiles is [Test 13: Density Inversion Test(p19)](https://cdn.ioos.noaa.gov/media/2020/03/QARTOD_TS_Manual_Update2_200324_final.pdf), which is still for the moment unavailable within the ioos_qc package. 
![QARTOD_TS_Manual_Update2_200324_final p.19](https://user-images.githubusercontent.com/30420025/102253984-eadc1e00-3ebc-11eb-9811-36527cebe898.png)

We present an implementation of this test within Pull Request #42 which can be applicable to multiple types of data like profile data and trajectory profile data. The test handles both automatically up and downcast data. The tool does not provide a way to compute potential density and expect it as an input. A computation of that density from core CTD variables could be implemented. 

We then hope to spread the result of this test to the corresponding associated variables and derived variables sea_water_salinity, sea_water_temperature, sea_water_conductivity, density, and potential density. 

Let me know if some changes are needed or if it corresponds to your expectations.

**Comment by kwilcox** [comment]
closed with https://github.com/ioos/ioos_qc/pull/42
