### ISSUE TITLE
QARTOD Spike_test: Adding an optional second method

### ISSUE THREAD

**Issue by JessyBarrette** [ioos/ioos_qc#48]
IOOS_QC QARTOD Spike_Test is a direct implementation of the spike test described within the [QARTOD Manual](https://cdn.ioos.noaa.gov/media/2020/03/QARTOD_TS_Manual_Update2_200324_final.pdf).  This algorithm is acting in some conditions similarly than the the rate_of_change test. We present here a potential implementation of an alternative method which will target exclusively the single spike values over a certain threshold.

I suggest implementing this second method as an option within the QARTOD spike_test via a _method_ optional input and keeping the original average method as the default one. 

The method consider essentially that a value N is flagged if the following conditions are respected:
* The absolute value of the difference between the value N and its preceding (N-1) and following value (N+1) is bigger than a threshold 
* The multiplication of both difference is smaller than 0 (opposite direction). 

"<a href="https://www.codecogs.com/eqnedit.php?latex=\text{if}\;&space;\begin{matrix}&space;|X_{N-1}-X_{N}|\\&space;|X_{N}-X_{N&plus;1}|&space;\end{matrix}&space;>&space;\text{threshold}&space;\;\land\;&space;\(X_{N-1}-X_{N}\)(X_{N}-X_{N&plus;1})<0\;&space;\text{Flag}\Rightarrow&space;X_N" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\text{if}\;&space;\begin{matrix}&space;|X_{N-1}-X_{N}|\\&space;|X_{N}-X_{N&plus;1}|&space;\end{matrix}&space;>&space;\text{threshold}&space;\;\land\;&space;\(X_{N-1}-X_{N}\)(X_{N}-X_{N&plus;1})<0\;&space;\text{Flag}\Rightarrow&space;X_N" title="\text{if}\; \begin{matrix} |X_{N-1}-X_{N}|\\ |X_{N}-X_{N+1}| \end{matrix} > \text{threshold} \;\land\; \(X_{N-1}-X_{N}\)(X_{N}-X_{N+1})<0\; \text{Flag}\Rightarrow X_N" /></a>"

 To highlight the difference between the two methods, an example can be find [here ](https://colab.research.google.com/drive/1d_bEYNXILmt4GpAQWHT0fZS1S0Q1ID-4?usp=sharing) within a jupyter notebook which is using the following vector and threshold values:
* [ 3 , 5 , 5 , 6 , 8 , 6 , 6 , 6.75 , 6 , 6 , 5.3 , 6 , 6 , 9 , 5 , None , 4 ]
* suspect threshold= 0.5
* fail threshold= 1

# Average Method (suggested by QARTOD)
By applying the regular QARTOD Spike method, we get the following result:
![image](https://user-images.githubusercontent.com/30420025/107834850-53743980-6d4c-11eb-96ea-22c52b2c5605.png)

# Differential Method (suggested alternative method)
Here's the results in similar conditions for the suggested differential method.
![image](https://user-images.githubusercontent.com/30420025/107835241-a0a4db00-6d4d-11eb-8985-7668568d6d42.png)

As shown, the second method only flag the single spike values without flagging records that are associated with a strong preceding jump. The QARTOD rate of change test can then be use to flag those data more rigorously if desired.

**Comment by kwilcox** [comment]
Fixed in https://github.com/ioos/ioos_qc/pull/50
