### ISSUE TITLE
Bug in creating a climatology with data that spans different years

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioos_qc#51]
See https://github.com/ioos/ioos_qc/blob/valid-range-test/ioos_qc/config_creator/config_creator.py#L397-L399
 
Changing [this notebook's](https://github.com/ioos/ioos_qc/blob/valid-range-test/docs/source/examples/storms_qc_test_1054.ipynb) `query_min_t` to be in 2020 will expose the bug. The end dates end up being before the start dates and no data is returned in the subset.

**Comment by yosoyjay** [comment]
Improvement in the handling of interpolation including a fix for this issue in 5c80088

**Comment by kwilcox** [comment]
Fix in https://github.com/ioos/ioos_qc/commit/5f41cc7c7e42324d31095c7c2a8f5b68c4eb23d4
