### ISSUE TITLE
conda install doesn't have latest version of qartod.py

### ISSUE THREAD

**Issue by jeffcnz** [ioos/ioos_qc#63]
Installing (or updating) ioos_qc from conda forge installs version 2, but without the updates to qartod.py spike_test.

The version installed doesn't have the method option, or the difference method available.

**Comment by kwilcox** [comment]
The updates to spike_test occured in https://github.com/ioos/ioos_qc/commit/fb3329da67486c43aa1fe70251465f5fa81f8582 which hasn't been released. I will cut a 2.0.1 release now!

**Comment by kwilcox** [comment]
The PyPI package is available: https://pypi.org/project/ioos-qc/#files

Waiting for the `conda-forge` bot to figure this out and PR the conda repository...

**Comment by kwilcox** [comment]
@jeffcnz please try installing 2.0.1
