### ISSUE TITLE
Drop pyproj

### ISSUE THREAD

**Issue by ocefpaf** [ioos/ioos_qc#72]
@kwilcox pyproj requires a wheel when using `pip` or the `proj` dependency when using a package manager. Would it be OK to use pygc or some other great circle computation instead? Using pyproj just for that is kind of on overkill.

My goal is to make `ioos_qc` installable and 100% usable on platforms where `proj` and binaries wheels are hard to install.

**Comment by kwilcox** [comment]
We [ran into problems ](https://github.com/ioos/ioos_qc/commit/524a85aba66e79ed910aa8343ba11d36be873ac2) using `pygc`, the same that are documented in [this issue](https://github.com/axiom-data-science/pygc/issues/4). We could add the loop parameter to `pygc` and then update that repo for GHA, cut a new version, etc. Or we could just copy and paste a pure python method into this repo that converges. I don't have a strong preference.

**Comment by ocefpaf** [comment]
> We [ran into problems ](https://github.com/ioos/ioos_qc/commit/524a85aba66e79ed910aa8343ba11d36be873ac2) using `pygc`, the same that are documented in [this issue](https://github.com/axiom-data-science/pygc/issues/4). We could add the loop parameter to `pygc` and then update that repo for GHA, cut a new version, etc. Or we could just copy and paste a pure python method into this repo that converges. I don't have a strong preference.

I can fix and do a new release. While vendoring that code here makes sense I do have other projects that may require the same "pyproj great circle drop" and will benefit from this. PRs incoming...

**Comment by ocefpaf** [comment]
Sent https://github.com/axiom-data-science/pygc/pull/6 and https://github.com/axiom-data-science/pygc/pull/7 your way but I've been thinking about using `geographiclib` instead. It is a solid library, well maintained, pure Python, and nailed this issue down already. What do you think? It would be one less lib to care for :-)
