### ISSUE TITLE
GSoC'23

### ISSUE THREAD

**Issue by ocefpaf** [ioos/ioos_qc#96]
IOOS is applying again for Google Summer of Code and, if selected, this are some ideas for participants to work with `ioos_qc`.

1. Improve Documentation and Examples: `ioos_qc` implements multiple QA/QC checks for a huge variety or datasets. An efficient documentation should be example driven. See https://github.com/ioos/ioos_qc/pull/94 for an example.
    - Implement notebooks with examples for datasets that are not covered but our documentation;
    - Improve the existing notebooks with updated syntax and simpler/easier to follow code.
2. Research and integrate other community based QC standards into `ioos_qc`. We want to enable _standardization of the code_ used to run QC checks in the ocean community. This will increase data transparency and lead to higher quality data. These can be implementations of the standards or wrappers around other libraries that provide a consistent `ioos_qc` interface and configuration.
    - HF Radar - [qccodar](https://github.com/nccoos/qccodar)
    - Gliders/UAVs
3. Simplify the deployment of `ioos_qc`. Currently `ioos_qc` is only a python library and implementation involves installing the library into a Python environment and configuring data pipelines to run `ioos_qc` directly. There could be simpler ways to package `ioos_qc` so it plugs into data piplelines without the direct code integration.
    - Package the `ioos_qc` library into an easy-to-use Docker image that can load data and configurations from mounted files and output other files.
    - Provide examples scripts and implementations of running `ioos_qc` in serverless environments such as [Knative](https://cloud.google.com/knative/).

- Skills required:
  - Python, documentation building, GitHub Actions
  - Some experience with time-series and/or location-based data
  - Docker, knative, serveless techniques

- Difficulty:
    - Moderate to hard depending of the size of the proposal

- Mentor(s): Kyle Wilcox

**Comment by AbhishekTiwari23** [comment]
Hello, I am Abhishek Tiwari. I am looking for projects that align with my technical abilities for the upcoming GSoC. I am pleased to have found the Improve Documentation and Examples(first one) project, which is a great match for my skill set. Please advise me on how I can become a stronger candidate for this project? Thank you.

**Comment by ocefpaf** [comment]
@AbhishekTiwari23 we are waiting for Google to approve us as an org first before engaging with prospective participants to avoid wasting your time.  Please stay tuned!

**Comment by AbhishekTiwari23** [comment]
I am also waiting, hoping for the best. Thanks

**Comment by AbhishekTiwari23** [comment]
Is the Organisation got selected?

**Comment by ocefpaf** [comment]
The final list will be published today by Google but we did not make the cut for 2023. Thanks for your interest. Closing this for now.
